CREATE TABLE KFTC_NOTIFICATION_HISTORY (
    KFTC_MESSAGE_NO        CHAR(12)      NOT NULL, -- 금결원 센터번호
    PROCESS_DATE           CHAR(8)       NOT NULL, -- 처리일자 (YYYYMMDD)
    ELECTRONIC_PAYMENT_NO  VARCHAR(30)   NOT NULL, -- 전자납부번호
    ESB_TX_ID              VARCHAR(40),            -- ESB 트랜젝션번호
    CONSTRAINT PK_KFTC_MESSAGE
        PRIMARY KEY (PROCESS_DATE, KFTC_MESSAGE_NO)
);

-- 테이블 코멘트
COMMENT ON TABLE KFTC_NOTIFICATION_HISTORY
IS '금결원 통지 이력';

-- 컬럼 코멘트
COMMENT ON COLUMN KFTC_NOTIFICATION_HISTORY.PROCESS_DATE
IS '처리일자 (YYYYMMDD)';

COMMENT ON COLUMN KFTC_NOTIFICATION_HISTORY.KFTC_MESSAGE_NO
IS '금결원 센터번호';

COMMENT ON COLUMN KFTC_NOTIFICATION_HISTORY.ELECTRONIC_PAYMENT_NO
IS '전자납부번호';

COMMENT ON COLUMN KFTC_NOTIFICATION_HISTORY.ESB_TX_ID
IS 'ESB 트랜젝션번호';


INSERT INTO KFTC_NOTIFICATION_HISTORY
(
    PROCESS_DATE,
    KFTC_MESSAGE_NO,
    ELECTRONIC_PAYMENT_NO,
    ESB_TX_ID
)
VALUES
(
    TO_CHAR(CURRENT_DATE, 'YYYYMMDD'),
    ?,
    ?,
    ?
);